### ISSUE TITLE
Docker build builds without errors, but logs say otherwise

### ISSUE THREAD

**Issue by SergeyMi37** [grongierisc/django-iris-template#1]
docker-compose build
docker-compose up -d
docker-compose logs
...
web_1   | nc: getaddrinfo for host "iris" port 1972: Temporary failure in name resolution
web_1   | nc: getaddrinfo for host "iris" port 1972: Temporary failure in name resolution
web_1   | nc: getaddrinfo for host "iris" port 1972: Temporary failure in name resolution
iris_1  | Durable folder: /durable/iris does not exists, or cannot be createdweb_1   | nc: getaddrinfo for host "iris" port 1972: Temporary failure in name resolution
web_1   | nc: getaddrinfo for host "iris" port 1972: Temporary failure in name resolution
web_1   | nc: getaddrinfo for host "iris" port 1972: Temporary failure in name resolution
...

**Comment by rcemper** [comment]
just did a check:  all OK
> docker-compose build --progress   plain  # creates  2 containers
> docker-compose up -d                      # all fine 
> docker-compose logs iris  -f              # all normal
>  docker-compose logs web  -f        
django-iris-template-web-1  | System check identified no issues (0 silenced).
django-iris-template-web-1  | May 31, 2023 - 19:48:19
django-iris-template-web-1  | Django version 4.0.10, using settings 'config.settings'
django-iris-template-web-1  | Starting development server at http://0.0.0.0:8000/
django-iris-template-web-1  | Quit the server with CONTROL-C.

BUT: Windows Docker Desktop is a beast.
- more than once I ran short of diskspace with total irrational side effects. 
- similar even after removing images some ports left blocked and unavailable
forcing restart of docker and even once the whole Windows,
